"""initial migration

Revision ID: 9d05398d17a5
Revises: b543794b104c
Create Date: 2017-01-07 22:41:55.865000

"""

# revision identifiers, used by Alembic.
revision = '9d05398d17a5'
down_revision = 'b543794b104c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
